---
# tasks file for osquery-role

- name: Install osquery on ubuntu
  ansible.builtin.include_tasks: setup-deb.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - configuration

- name: Install osquery on centos
  ansible.builtin.include_tasks: setup-rpm.yml
  when: ansible_distribution == "CentOS"
  tags:
    - configuration

- name: Copy configuration file
  ansible.builtin.copy:
    src: "osquery.conf"
    dest: "{{ osquery_destination }}/osquery.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
  notify: restart osquery

- name: Copy query packs
  ansible.builtin.copy:
    src: packs/
    dest: "{{ osquery_destination }}/packs"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
  notify: restart osquery

- name: Copy query flags
  ansible.builtin.copy:
    src: "osquery.flags"
    dest: "{{ osquery_destination }}/osquery.flags"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
  notify: restart osquery

- name: Daemon osquery starts on boot
  become: true
  ansible.builtin.service:
    name: "{{ osquery_daemon }}"
    state: started
    enabled: yes
  tags:
    - configuration

