---
# playbooks file
# ansible-playbook example.yml --tags "configuration,runsc"

- name: "BE S.A - Security Compliance v1.0"
  hosts: linux
  become: yes

  roles:
    - lynis-role
    - osquery-role
...
